### ISSUE TITLE
adding ssh for remote overwatch

### ISSUE THREAD

**Issue by rayzer86** [Heckie75/voltcraft-sem-6000#11]
Hi!

It works perfectly with my voltcraft.
But i had an idea, would it be to difficult to add an ssh function?
For example:
`./sem-6000.exp Voltcraft -r 192.168.0.1 --status --print`

Why?
Example; A freebsd server, that has no bluetooth capabilities but still wants to serve energy consumption data to a webpage.  
Thanks for great code!

**Comment by ckujau** [comment]
The machine executing `sem-6000.exp` needs bluetooth capabilities of course, so to transfer its output to a web server one could do:

`./sem-6000.exp Voltcraft --status --print | ssh 192.168.0.1 "cat > /var/www/output.txt"`

But, maybe I misunderstood and this report is about something else?

**Comment by everything-everything** [comment]
> Hi!
> 
> It works perfectly with my voltcraft.
> But i had an idea, would it be to difficult to add an ssh function?
> For example:
> `./sem-6000.exp Voltcraft -r 192.168.0.1 --status --print`
> 
> Why?
> Example; A freebsd server, that has no bluetooth capabilities but still wants to serve energy consumption data to a webpage.
> Thanks for great code!

you can fix this :) 

open sem6000.exp in a Editor (nano, tilde, Notepad++ or what you want)
search the line :
set KNOWN_SEMS_FILE            "~/.known_sem6"
edit it to 
set KNOWN_SEMS_FILE            "./known_sem6.config"
make new file that is in the folder of sem6000.exp.

Explanation. the ./.known_sem6 file is file that is hidden. SSH don't find the hidden config. so rename it to an non hidden file.
