### ISSUE TITLE
Consumption trigger problem

### ISSUE THREAD

**Issue by Duanoc** [Heckie75/voltcraft-sem-6000#16]
The consumption statistics can be read, start time can be set and it can be reset to 0. But in my case it does not start counting the consumption. The current consumption is read out correctly, but the consumption for the last hour, day, etc. stays 0. I read out via bluetooth with an raspberry pi and the LED ring keeps blinking blue.
But if the voltcraft App once started then the LED ring turns automatically green and I can stop the app again. Now the consumption per hour, day, etc. starts  growing. Is there a way to trigger the "voltcraft sem" like the APP to not manually have to activate it (which signal is send to the "voltcraft sem" from the APP)?

**Comment by Heckie75** [comment]
First of all you have to sync the device so that time is set. Have you already tried it?

**Comment by Duanoc** [comment]
You are right, `--sync` solves the problem. I didn't get it from the README, that `--sync` is essential for getting `consumption`. I just had `--data reset` and `--statistics set mm-dd 00:00`. Maybe you can add that hint in the README.
