### ISSUE TITLE
Only working with firmware 1.16?

### ISSUE THREAD

**Issue by MikeQufi** [Heckie75/voltcraft-sem-6000#17]
Hi,
first of all: thanks for this great project.
I've used this to get remote access to my power plugs for a long time. For some reason I installed the app and when I connected the plugs, the app told me that there is a firmware update. I did the update, my plugs firmware is now on version 1.22 and I cannot connect with this project :(
Is there any hope for me to get it working again, either by downgrading the firmware (is it possible? if yes, how?) or by an adopted version of this project?
Kind Regards, Mike

**Comment by Heckie75** [comment]
May be you can turn on debugging and verbose mode of the script in order to get more details and to understand where the problem is.

**Comment by MikeQufi** [comment]
Hi Heckie,
thanks for your reply. I just did some research and I found out that is not sufficient to put the device where the app is installed asside. The app seems to connect to the plug even when the device is in standby mode.
So the app was connected and I could not connect with your code. Now I stopped the app and everything is fine again.
Sorry, my fault.
