### ISSUE TITLE
It's possible to connect Voltcraft SEM-6000 to Arduino ESP32?

### ISSUE THREAD

**Issue by Igni99** [Heckie75/voltcraft-sem-6000#19]
I'm currently working with a ESP32 S3 Arduino board and I don't know how I can connect ESP32 S3 BLE to Voltcraft. There is a datasheet where all the bluetooth specifications?

**Comment by Heckie75** [comment]
Maybe take a look at https://github.com/Heckie75/voltcraft-sem-6000/blob/master/API.md

**Comment by Igni99** [comment]
Thanks for all the API.md information. Now I'm able to connect the ESP32 S3 with the Voltcraft. At first I tought that the problem was that I didn't know how to send the commands, but the real problem was that I wasn't sending the autentification code first.
