### ISSUE TITLE
Integration into lm_sensors

### ISSUE THREAD

**Issue by MarcMagneto** [Heckie75/voltcraft-sem-6000#3]
Hello,
any chance to integrate the --measure command into lm_sensors? If the values like voltage, ampere and power became familiar to sensors, one could easily make nice looking realtime plots with KSysGuard for example.

**Comment by Heckie75** [comment]
Actually, I think that ```lm_sensors``` is something that is used for measuring temperature of cpu and mainboard. I have no idea how to integrate it. Sorry.
