### ISSUE TITLE
Power factor not in --status --json output

### ISSUE THREAD

**Issue by cmur2** [Heckie75/voltcraft-sem-6000#4]
The `--status --print` human readable output also shows the calculated the power factor ([source](https://github.com/Heckie75/voltcraft-sem-6000/blob/master/sem-6000.exp#L366)) but the `--status --json` output does not include it ([source](https://github.com/Heckie75/voltcraft-sem-6000/blob/master/sem-6000.exp#L596-L603)). I see that the power factor [can be calculated](https://github.com/Heckie75/voltcraft-sem-6000/blob/master/sem-6000.exp#L332-L346) from the other values in the JSON output but maybe it would be easier to include it directly? Or is there a downside in doing that?

Also wanted to say: cool project and reverse engineering, thanks!

**Comment by Heckie75** [comment]
Hi, I have added the power factor in json format. 

thanks and happy easter
